


#spring.application.name=Tulja-Bhavani-World
#
#spring.mvc.view.prefix=/WEB-INF/view/
#spring.mvc.view.suffix=.jsp
#
## Database connection (MySQL Example)
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:TuljaBhavaniWorld}?createDatabaseIfNotExist=true
#spring.datasource.username=${DB_USERNAME:root}
#spring.datasource.password=${DB_PASSWORD:}
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#
##Server configuration
#server.port=8080
##server.servlet.context-path=/ems
#
#
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=tuljabhavaniworld@gmail.com
#spring.mail.password=${MAIL_PASSWORD:}
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#
#manager.email=tuljabhavaniworld@gmail.com

#=========================#

spring.application.name=Tulja-Bhavani-World

spring.mvc.view.prefix=/WEB-INF/view/
spring.mvc.view.suffix=.jsp

# Database connection (MySQL Example)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/TuljaBhavaniWorld?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server configuration
server.port=8080
#server.servlet.context-path=/ems


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tuljabhavaniworld@gmail.com
spring.mail.password=Sa@9108534041
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

manager.email=tuljabhavaniworld@gmail.com

